### ISSUE TITLE
server: ttn2dballe Too many open files

### ISSUE THREAD

**Issue by pat1** [r-map/rmap#268]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
  File "/usr/lib64/python2.7/threading.py", line 757, in run
  File "/home/pat1/git/rmap/python/paho/mqtt/client.py", line 2289, in _thread_main
  File "/home/pat1/git/rmap/python/paho/mqtt/client.py", line 1263, in loop_forever
  File "/home/pat1/git/rmap/python/paho/mqtt/client.py", line 813, in loop
  File "/home/pat1/git/rmap/python/paho/mqtt/client.py", line 1075, in loop_read
  File "/home/pat1/git/rmap/python/paho/mqtt/client.py", line 1477, in _packet_read
  File "/home/pat1/git/rmap/python/paho/mqtt/client.py", line 1945, in _packet_handle
  File "/home/pat1/git/rmap/python/paho/mqtt/client.py", line 2120, in _handle_publish
  File "/home/pat1/git/rmap/python/paho/mqtt/client.py", line 2276, in _handle_on_message
  File "/home/pat1/git/rmap/python/rmap/ttn2dballe.py", line 219, in on_message
  File "/home/pat1/git/rmap/python/rmap/rmapmqtt.py", line 82, in __init__
  File "/home/pat1/git/rmap/python/paho/mqtt/client.py", line 424, in __init__
  File "/home/pat1/git/rmap/python/paho/mqtt/client.py", line 264, in _socketpair_compat
  File "/usr/lib64/python2.7/socket.py", line 191, in __init__
error: [Errno 24] Too many open files

The problems are two:
* the error "Too many open files"
* the thread do not restart on this error

**Comment by pat1** [comment]
related to https://github.com/eclipse/paho.mqtt.python/issues/170

**Comment by pat1** [comment]
2018-01-18 22:05:48 - root - ERROR - 140428483368704 - Exception occured: [Errno 24] Too many open files
2018-01-18 22:05:48 - root - ERROR - 140428483368704 - Traceback (most recent call last):
  File "/home/pat1/git/rmap/python/rmap/ttn2dballe.py", line 221, in on_message
  File "/home/pat1/git/rmap/python/rmap/rmapmqtt.py", line 83, in __init__
  File "/home/pat1/git/rmap/python/paho/mqtt/client.py", line 498, in __init__
  File "/home/pat1/git/rmap/python/paho/mqtt/client.py", line 249, in _socketpair_compat
  File "/usr/lib64/python2.7/socket.py", line 206, in accept
error: [Errno 24] Too many open files
